In [ ]:
import numpy as np
import pandas as pd

from google.colab import files
import io 
 
uploaded = files.upload()

Saving iphone_purchase_records.csv to iphone_purchase_records.csv


In [ ]:
iphone_purchases = pd.read_csv(io.BytesIO(uploaded['iphone_purchase_records.csv']))


In [ ]:
iphone_purchases['Purchase Iphone'].value_counts().to_frame().T

0    1
Purchase Iphone  257  143

In [ ]:
iphone_purchases.shape

(400, 4)

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [ ]:
X = iphone_purchases.drop(["Purchase Iphone","Gender"], axis=1)
y = iphone_purchases["Purchase Iphone"]




In [ ]:
#part 1: split the dataset into train and testing
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.8)


In [ ]:
#part 1: standardize the x_train and x_test
X_train_standardized = scaler.fit_transform(X_train)
X_test_standardized = scaler.fit_transform(X_test)





In [ ]:
def fold_i_of_k(dataset, i, k):
  n = len(dataset)
  return dataset[n*(i-1)//k:n*i//k]

In [ ]:
# Our training dataset has 320 samples.  Let's create 10 folds.  Each fold with have 32 samples.


X_train1 = X_train_standardized[:31]
X_train2 = X_train_standardized[32:63]
X_train3 = X_train_standardized[64:95]
X_train4 = X_train_standardized[96:127]
X_train5 = X_train_standardized[128:159]
#X_train6 = X_train_standardized[160:191]
#X_train7 = X_train_standardized[192:223]
#X_train8 = X_train_standardized[224:255]
#X_train9 = X_train_standardized[256:287]
#X_train10 = X_train_standardized[288:319]





y_train1 = y_train[:31]
y_train2 = y_train[32:63]
y_train3 = y_train[64:95]
y_train4 = y_train[96:127]
y_train5 = y_train[128:159]
#y_train6 = y_train[160:191]
#y_train7 = y_train[192:223]
#y_train8 = y_train[224:255]
#y_train9 = y_train[256:287]
#y_train10 = y_train[288:319]



In [ ]:
X1 = np.concatenate([X_train1,X_train2, X_train3, X_train4]) # Keep fold 5 out and use for testing
X2 = np.concatenate([X_train1,X_train2, X_train3, X_train5]) # Keep fold 4 out and use for testing
X3 = np.concatenate([X_train1,X_train2, X_train4, X_train5]) # Keep fold 3 out and use for testing
X4 = np.concatenate([X_train1,X_train3, X_train4, X_train4]) # Keep fold 2 out and use for testing
X5 = np.concatenate([X_train2,X_train3, X_train4, X_train5]) # Keep fold 1 out and use for testing




In [ ]:
y1 = np.concatenate([y_train1,y_train2, y_train3, y_train4]) # Keep fold 5 out and use for testing
y2 = np.concatenate([y_train1,y_train2, y_train3, y_train5]) # Keep fold 4 out and use for testing
y3 = np.concatenate([y_train1,y_train2, y_train4, y_train5]) # Keep fold 3 out and use for testing
y4 = np.concatenate([y_train1,y_train3, y_train4, y_train4]) # Keep fold 2 out and use for testing
y5 = np.concatenate([y_train2,y_train3, y_train4, y_train5]) # Keep fold 1 out and use for testing



In [ ]:
#use k-fold cross validation to get the accuracy for the folds

from sklearn import svm
from sklearn.metrics import confusion_matrix, accuracy_score


svc = svm.SVC(kernel= 'linear', random_state=0, C=1.0, tol=0.001)
svc.fit(X1,y1)
y_predict_5 =svc.predict(X_train5)

matrix5 = confusion_matrix(y_train5, y_predict_5)
print(matrix5)
Accuracy5 = accuracy_score(y_train5, y_predict_5)

print ("fifth fold  accuracy is %f" %Accuracy5)


svc.fit(X2,y2)
y_predict_4 =svc.predict(X_train4)

matrix4 = confusion_matrix(y_train4, y_predict_4)
print(matrix4)
Accuracy4 = accuracy_score(y_train4, y_predict_4)

print ("fourth fold  accuracy is %f" %Accuracy4)


svc.fit(X3,y3)
y_predict_3 =svc.predict(X_train3)

matrix3 = confusion_matrix(y_train3, y_predict_3)
print(matrix3)
Accuracy3 = accuracy_score(y_train3, y_predict_3)

print ("third fold  accuracy is %f" %Accuracy3)

svc.fit(X4,y4)
y_predict_2 =svc.predict(X_train2)

matrix2 = confusion_matrix(y_train2, y_predict_2)
print(matrix2)
Accuracy2 = accuracy_score(y_train2, y_predict_2)

print ("second fold  accuracy is %f" %Accuracy2)

svc.fit(X5,y5)
y_predict_1 =svc.predict(X_train1)

matrix1 = confusion_matrix(y_train1, y_predict_1)
print(matrix1)
Accuracy1 = accuracy_score(y_train1, y_predict_1)

print ("first fold  accuracy is %f" %Accuracy1)

























[[19  3]
 [ 2  7]]
fifth fold  accuracy is 0.838710
[[12  2]
 [ 8  9]]
fourth fold  accuracy is 0.677419
[[16  1]
 [ 6  8]]
third fold  accuracy is 0.774194
[[19  4]
 [ 3  5]]
second fold  accuracy is 0.774194
[[19  1]
 [ 5  6]]
first fold  accuracy is 0.806452


In [ ]:
total = Accuracy1 + Accuracy2 + Accuracy3 + Accuracy4 + Accuracy5
mean = total / 5
print(mean)

0.7741935483870968


In [ ]:
#part 3: implementing grid search
from sklearn import metrics

#The first value in the tuple is c value and the second is the tolerance
parameters = [(1.53, 0.1), (0.28, 0.21),(0.45, 0.34), (0.60,0.90)]



for b in range (len(parameters)):
#print(parameters[b][0])
  svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=parameters[b][0], tol=parameters[b][1])
  svm_grid_search.fit(X1 ,y1)
  y_predict5 = svm_grid_search.predict(X_train5)
  print("C parameter is %.2f and tolerance is %.2f" %(parameters[b][0], parameters[b][1]),"Accuracy:",metrics.accuracy_score(y_train5, y_predict5))





C parameter is 1.53 and tolerance is 0.10 Accuracy: 0.8387096774193549
C parameter is 0.28 and tolerance is 0.21 Accuracy: 0.8387096774193549
C parameter is 0.45 and tolerance is 0.34 Accuracy: 0.8387096774193549
C parameter is 0.60 and tolerance is 0.90 Accuracy: 0.8709677419354839


In [ ]:
for b in range (len(parameters)):
#print(parameters[b][0])
  svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=parameters[b][0], tol=parameters[b][1])
  svm_grid_search.fit(X2 ,y2)
  y_predict4 = svm_grid_search.predict(X_train4)
  print("C parameter is %.2f and tolerance is %.2f" %(parameters[b][0], parameters[b][1]),"Accuracy:",metrics.accuracy_score(y_train4, y_predict4))



C parameter is 1.53 and tolerance is 0.10 Accuracy: 0.6774193548387096
C parameter is 0.28 and tolerance is 0.21 Accuracy: 0.6774193548387096
C parameter is 0.45 and tolerance is 0.34 Accuracy: 0.6774193548387096
C parameter is 0.60 and tolerance is 0.90 Accuracy: 0.6774193548387096


In [ ]:
for b in range (len(parameters)):
#print(parameters[b][0])
  svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=parameters[b][0], tol=parameters[b][1])
  svm_grid_search.fit(X3 ,y3)
  y_predict3 = svm_grid_search.predict(X_train3)
  print("C parameter is %.2f and tolerance is %.2f" %(parameters[b][0], parameters[b][1]),"Accuracy:",metrics.accuracy_score(y_train3, y_predict3))



C parameter is 1.53 and tolerance is 0.10 Accuracy: 0.7741935483870968
C parameter is 0.28 and tolerance is 0.21 Accuracy: 0.7096774193548387
C parameter is 0.45 and tolerance is 0.34 Accuracy: 0.8064516129032258
C parameter is 0.60 and tolerance is 0.90 Accuracy: 0.7096774193548387


In [ ]:
for b in range (len(parameters)):
#print(parameters[b][0])
  svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=parameters[b][0], tol=parameters[b][1])
  svm_grid_search.fit(X2 ,y2)
  y_predict2 = svm_grid_search.predict(X_train2)
  print("C parameter is %.2f and tolerance is %.2f" %(parameters[b][0], parameters[b][1]),"Accuracy:",metrics.accuracy_score(y_train2, y_predict2))



C parameter is 1.53 and tolerance is 0.10 Accuracy: 0.8064516129032258
C parameter is 0.28 and tolerance is 0.21 Accuracy: 0.8064516129032258
C parameter is 0.45 and tolerance is 0.34 Accuracy: 0.8387096774193549
C parameter is 0.60 and tolerance is 0.90 Accuracy: 0.8064516129032258


In [ ]:
for b in range (len(parameters)):
#print(parameters[b][0])
  svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=parameters[b][0], tol=parameters[b][1])
  svm_grid_search.fit(X1 ,y1)
  y_predict1 = svm_grid_search.predict(X_train1)
  print("C parameter is %.2f and tolerance is %.2f" %(parameters[b][0], parameters[b][1]),"Accuracy:",metrics.accuracy_score(y_train1, y_predict1))



C parameter is 1.53 and tolerance is 0.10 Accuracy: 0.8387096774193549
C parameter is 0.28 and tolerance is 0.21 Accuracy: 0.8387096774193549
C parameter is 0.45 and tolerance is 0.34 Accuracy: 0.8387096774193549
C parameter is 0.60 and tolerance is 0.90 Accuracy: 0.8064516129032258


In [ ]:
#part 4: evaluating the best model and reporting the performance 

#here we use svm with 0.60 for the c value and 0.90 for the tolerance 


svm_grid_search = svm.SVC(kernel= 'linear', random_state=0, C=0.60, tol=0.90)
svm_grid_search.fit(X_train_standardized ,y_train)
y_prediction = svm_grid_search.predict(X_test_standardized)
print("Accuracy:",metrics.accuracy_score(y_test, y_prediction))

























Accuracy: 0.7875
